version: "2"
run:
  concurrency: 4
  timeout: 3m
  # Keep exit code 0 until we fix all this, i.e. get the baseline set.
  issues-exit-code: 0
  # Keep this false until we address all the non-test files and set baseline.
  tests: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  path-prefix: ""

linters:
  enable:
    - staticcheck
    - govet
    - gosec
    - misspell
    - nakedret
    - revive
    - unconvert

  disable:
    - errcheck
    - goconst
    - ineffassign
    - lll
    - unused

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:
      # We don't control the ciphers as we are just implementing standards.
      - linters:
          - gosec
        text: "weak cryptographic primitive"

    paths:
      - testdata
      - ".*_test.go$"

formatters:
  exclusions:
    generated: lax
